# PCDCollection.srv

# goal definition
# this section defines the inputs necessary to complete the goal

string manipulator
string read_path
string write_path

---

# result definition
# this section defines the outputs of the completed action

bool success

---

# feedback definition

float64 progress