# PCDCollection.action

# goal definition
# this section defines the inputs necessary to complete the action

string manipulator
string read_path
string write_directory

---

# result definition
# this section defines the outputs of the completed action

bool success

---

# feedback definition
# this section defines the intermediate feedback of the action

float64 progress