# PCDRegistration.srv

# request definition
# this section defines the inputs necessary to complete the service

string[] manipulators
string scans_path
string model_path

---

# response definition
# this section defines the outputs of the completed service

string write_path
